name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn test
    - name: Deploy
      run: mkdir staging && cp target/*.jar staging
    - name: Just for Fun an LS
      run: ls -al target
    - name: Set Executable Permissions
      run: chmod +x target/Revival-1.0.1-SNAPSHOT.jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Revival
        path: target/Revival-1.0.1-SNAPSHOT.jar
